export enum PaymentStatus {
  PENDING = "PENDING",
  REQUIRES_ACTION = "REQUIRES_ACTION",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
  REFUNDED = "REFUNDED",
}
