export enum TicketStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_FOR_USER = "WAITING_FOR_USER",
  WAITING_FOR_SUPPORT = "WAITING_FOR_SUPPORT",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}
